services:
  wurst:
    image: frotty/wurstscript:latest
    user: root
    working_dir: /workspace
    environment:
      JAVA_TOOL_OPTIONS: -Duser.home=/tmp
    volumes:
      - .:/workspace
    command: ./build.sh
